version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: benefits
      POSTGRES_PASSWORD: benefits_pw
      POSTGRES_DB: benefits
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benefits -d benefits_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
    image: elasticsearch:8.10.2
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  api-gateway:
    build: ./apps/api-gateway
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  user-service:
    build: ./services/user-svc
    ports:
      - "7001:7001"
    environment:
      DATABASE_URL: postgresql://benefits:benefits_pw@postgres:5432/benefits
    depends_on:
      - postgres

  benefits-service:
    build: ./services/benefits-svc
    ports:
      - "7002:7002"
    environment:
      DATABASE_URL: postgresql://benefits:benefits_pw@postgres:5432/benefits
    depends_on:
      - postgres

  employee-portal:
    build: ./apps/employee-portal
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - benefits-service

  admin-dashboard:
    build: ./apps/admin-dashboard
    ports:
      - "3001:3001"
    depends_on:
      - user-service
      - benefits-service

volumes:
  postgres_data:
