#!/bin/bash
echo "Build Verification Report"
echo "========================"
echo "✓ Database: $(docker ps | grep postgres > /dev/null && echo "Running" || echo "Not running")"
echo "✓ Encryption: $(node test-encryption-complete.js 2>/dev/null | grep "ALL TESTS PASSED" > /dev/null && echo "Working" || echo "Failed")"
echo "✓ Services: $(ls -d ../../services/*/ 2>/dev/null | wc -l) services created"
echo "✓ Apps: $(ls -d ../../apps/*/ 2>/dev/null | wc -l) applications created"
echo "✓ Docker Compose: $([ -f ../../docker-compose.yml ] && echo "Ready" || echo "Missing")"
echo ""
echo "Next steps:"
echo "1. Start all services: docker-compose up"
echo "2. Access Employee Portal: http://localhost:3000"
echo "3. Access Admin Dashboard: http://localhost:3001"
echo "4. API Health Checks: http://localhost:7001/health"
