name: Dependency Version Check

on:
  push:
    branches: [main, develop]
    paths:
      - 'scripts/check-versions.sh'
      - '.github/workflows/dependency-check.yml'
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  version-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Make script executable
        run: chmod +x ./scripts/check-versions.sh
      
      - name: Run version checks
        id: version_check
        run: |
          ./scripts/check-versions.sh > version-report.txt 2>&1
          echo "::set-output name=report::$(cat version-report.txt)"
        continue-on-error: true
      
      - name: Upload version report
        uses: actions/upload-artifact@v3
        with:
          name: version-report-${{ matrix.os }}
          path: version-report.txt
      
      - name: Comment PR with version status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('version-report.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📋 Dependency Version Check\n\u0060\u0060\u0060\n${report}\n\u0060\u0060\u0060`
            });
      
      - name: Fail if critical dependencies missing
        run: |
          if grep -q "❌" version-report.txt; then
            echo "Critical dependencies are missing!"
            exit 1
          fi
